---

- name: Convert credentials
  ansible.builtin.set_fact:
    __awx_credentials1: >
      {{ __awx_credentials1 +
        [{
          'name': item.name,
          'description': item.description,
          'organization': (item.organization.name if item.organization.name is defined else None),
          'credential_type': (item.credential_type.name if item.credential_type.name is defined else None),
          'update_secret': false,
          'inputs': item.inputs
        }]
      }}
  loop: "{{ __awx_credentials }}"
  loop_control:
    label:
      - "{{ item.name }}"
