---

- name: Convert credential_types
  ansible.builtin.set_fact:
    __awx_credential_types1: >
      {{ __awx_credential_types1 +
        [{
          'name': varss.name,
          'kind': varss.kind,
          'description': varss.description
        }]
      }}
  loop: "{{ __awx_credential_types }}"
  loop_control:
    loop_var: varss
    label: "{{ varss.name }}"

- name: Write credential_type/inputs to file (JSON)
  ansible.builtin.template:
    src: extract2json.j2
    dest: "{{ awx_config_path }}/credential_types/inputs/{{ varss.name | regex_replace('/', '@@') }}.json"
    mode: "0640"
  vars:
    extra_vars: "{{ varss.inputs }}"
  loop: "{{ __awx_credential_types }}"
  loop_control:
    loop_var: varss
    label: "{{ varss.name }}"
  when:
    - varss.inputs | length > 0
    - varss.inputs != "---"
    - varss.inputs != "{}"

- name: Write credential_type/injectors to file (JSON)
  ansible.builtin.template:
    src: extract2json.j2
    dest: "{{ awx_config_path }}/credential_types/injectors/{{ varss.name }}.json"
    mode: "0640"
  vars:
    extra_vars: "{{ varss.injectors }}"
  loop: "{{ __awx_credential_types }}"
  loop_control:
    loop_var: varss
    label: "{{ varss.name }}"
  when:
    - varss.injectors | length > 0
    - varss.injectors != "---"
    - varss.injectors != "{}"
