---

- name: Import dict w/ groups vs children&hosts
  ansible.builtin.set_fact:
    groups_dict: >-
      {{ lookup('file', awx_export_path + '/groups+children+hosts.json') | from_json }}

- name: Convert groups
  ansible.builtin.set_fact:
    __awx_groups1: >
      {{ __awx_groups1 | default([]) +
        [{
          'name': item.name,
          'inventory': item.summary_fields.inventory.name,
          'description': item.description,
          'hosts': groups_dict[__name]['hosts'],
          'children': groups_dict[__name]['children']
        }]
      }}
  vars:
    __name: "{{ item.name + '-' + item.id | string }}"
  loop: "{{ __awx_groups }}"
  loop_control:
    label:
      - "{{ item.name }}"
  when: item.name is not search('-')

- name: Write groups/variables to file (JSON)
  ansible.builtin.template:
    src: extract2json.j2
    dest: "{{ awx_config_path }}/groups/variables/{{ varss.name }}.json"
    mode: "0640"
  vars:
    extra_vars: "{{ varss.variables }}"
  loop: "{{ __awx_groups }}"
  loop_control:
    loop_var: varss
    label:
      - "{{ varss.name }}"
  when:
    - varss.variables | length > 0
    - varss.variables != "---"
    - varss.variables != "{}"
