---

- name: Convert hosts
  ansible.builtin.set_fact:
    __awx_hosts1: >
      {{ __awx_hosts1 | default([]) +
        [{
          'name': item.name,
          'inventory': item.summary_fields.inventory.name,
          'description': item.description
        }]
      }}
  loop: "{{ __awx_hosts }}"
  loop_control:
    label:
      - "{{ item.name }}"

- name: Write hosts/variables to file (JSON)
  ansible.builtin.template:
    src: extract2json.j2
    dest: "{{ awx_config_path }}/hosts/variables/{{ varss.name }}.json"
    mode: "0640"
  vars:
    extra_vars: "{{ varss.variables }}"
  loop: "{{ __awx_hosts }}"
  loop_control:
    loop_var: varss
    label:
      - "{{ varss.name }}"
  when:
    - varss.variables | length > 0
    - varss.variables != "---"
    - varss.variables != "{}"
