---

- name: Retrieve hosts from specific host export
  when: not awx_extract_from_inventory | bool
  block:

    - name: Convert hosts
      ansible.builtin.set_fact:
        __awx_hosts1: >
          {{ __awx_hosts1 | default([]) +
            [{
              'name': item.name,
              'inventory': item.summary_fields.inventory.name,
              'description': item.description
            }]
          }}
      loop: "{{ __awx_hosts | default([]) }}"
      loop_control:
        label:
          - "{{ item.name }}"

    - name: Write hosts/variables to file (JSON)
      ansible.builtin.template:
        src: extract2json.j2
        dest: "{{ awx_config_path }}/hosts/variables/{{ varss.name }}.json"
        mode: "0640"
      vars:
        extra_vars: "{{ varss.variables }}"
      loop: "{{ __awx_hosts | default([]) }}"
      loop_control:
        loop_var: varss
        label:
          - "{{ varss.name }}"
      when:
        - varss.variables | length > 0
        - varss.variables != "---"
        - varss.variables != "{}"

- name: Retrieve hosts from inventory
  when: awx_extract_from_inventory | bool
  block:

    - name: Import inventory file
      ansible.builtin.set_fact:
        inventory: >-
          {{ lookup('file', awx_export_path + '/inventory.json') | from_json }}

    - name: Loop over all inventories and get hosts
      ansible.builtin.set_fact:
        __awx_hosts1: >
          [
          {%- for inventory in inventory.assets.inventory -%}
          {% set outer_loop = loop %}
          {%- for host in inventory.related.hosts -%}
          {{
            {
              'name': host.name,
              'inventory': inventory.name,
              'description': host.description
            }
          }}
          {{ '' if (outer_loop.last and loop.last) else ',' }}
          {%- endfor -%}
          {%- endfor -%}
          ]
        __awx_host_vars: >
          [
          {%- for inventory in inventory.assets.inventory -%}
          {% set outer_loop = loop %}
          {%- for host in inventory.related.hosts -%}
          {{
            {
              'name': host.name,
              'variables': host.variables
            }
          }}
          {{ '' if (outer_loop.last and loop.last) else ',' }}
          {%- endfor -%}
          {%- endfor -%}
          ]

    - name: Write hosts/variables to file (JSON)
      ansible.builtin.template:
        src: extract2json.j2
        dest: "{{ awx_config_path }}/hosts/variables/{{ varss.name }}.json"
        mode: "0640"
      vars:
        extra_vars: "{{ varss.variables }}"
      loop: "{{ __awx_host_vars | default([]) }}"
      loop_control:
        loop_var: varss
        label:
          - "{{ varss.name }}"
      when:
        - varss.variables | length > 0
        - varss.variables != "---"
        - varss.variables != "{}"

    - name: Show all hosts present
      ansible.builtin.debug:
        msg: "{{ __awx_hosts1 | json_query('[].name') }}"
