---

- name: Convert schedules
  ansible.builtin.set_fact:
    __awx_schedules1: >-
      [
        {% for item in __awx_schedules %}
        {
          'name': '{{ item.name }}',
          'description': '{{ item.description }}',
          'inventory': '{{ (item.summary_fields.inventory.name if item.summary_fields.inventory.name is defined else None) }}',
          'rrule': '{{ item.rrule }}',
          'unified_job_template': '{{ item.summary_fields.unified_job_template.name }}'
        }{{ ',' if not loop.last else '' }}
        {% endfor %}
      ]

- name: Write schedules/extra_data to file (JSON)
  ansible.builtin.template:
    src: extract2json.j2
    dest: "{{ awx_config_path }}/schedules/extra_data/{{ varss.name }}.json"
    mode: "0640"
  vars:
    extra_vars: "{{ varss.extra_data }}"
  loop: "{{ __awx_schedules }}"
  loop_control:
    loop_var: varss
    label:
      - "{{ varss.name }}"
  when:
    - varss.extra_data | length > 0
    - varss.extra_data != "---"
    - varss.extra_data != "{}"
