---

- name: Converge pre playbook
  ansible.builtin.import_playbook: converge-pre.yml

- name: Converge
  hosts: all
  become: "no"
  vars:
    awx_export_path: /tmp/awx
    awx_config_path: /tmp/awx1
  tasks:
    - name: Include role 'awx_convert'
      ansible.builtin.include_role:
        name: awx_convert
